[package]
name = "mbox-prime"
version = "0.1.0"
authors = ["Charles Katzer <ckatzer@gmail.com>"]

[dependencies]
tui = "0.2.3"
termion = "1.5.1"
email = { git = "https://github.com/ckatzer4/rust-email" , rev = "44a76b984c27f588be36c9cb69fa18310934c083" }
mbox-reader = "0.1"
